# Constraints specific to null_algo

add_cells_to_pblock [get_pblocks payload_0] [get_cells -quiet [list formatter/rgen[0]*]]
add_cells_to_pblock [get_pblocks payload_1] [get_cells -quiet [list formatter/rgen[1]*]]
add_cells_to_pblock [get_pblocks payload_2] [get_cells -quiet [list formatter/rgen[2]*]]
add_cells_to_pblock [get_pblocks payload_3] [get_cells -quiet [list formatter/rgen[3]*]]
add_cells_to_pblock [get_pblocks payload_4] [get_cells -quiet [list formatter/rgen[4]*]]
add_cells_to_pblock [get_pblocks payload_5] [get_cells -quiet [list formatter/rgen[5]*]]
add_cells_to_pblock [get_pblocks payload_6] [get_cells -quiet [list formatter/rgen[6]*]]
add_cells_to_pblock [get_pblocks payload_7] [get_cells -quiet [list formatter/rgen[7]*]]
add_cells_to_pblock [get_pblocks payload_8] [get_cells -quiet [list formatter/rgen[8]*]]
add_cells_to_pblock [get_pblocks payload_9] [get_cells -quiet [list formatter/rgen[9]*]]
add_cells_to_pblock [get_pblocks payload_10] [get_cells -quiet [list formatter/rgen[10]*]]
add_cells_to_pblock [get_pblocks payload_11] [get_cells -quiet [list formatter/rgen[11]*]]
add_cells_to_pblock [get_pblocks payload_12] [get_cells -quiet [list formatter/rgen[12]*]]
add_cells_to_pblock [get_pblocks payload_13] [get_cells -quiet [list formatter/rgen[13]*]]
add_cells_to_pblock [get_pblocks payload_14] [get_cells -quiet [list formatter/rgen[14]*]]
add_cells_to_pblock [get_pblocks payload_15] [get_cells -quiet [list formatter/rgen[15]*]]
add_cells_to_pblock [get_pblocks payload_16] [get_cells -quiet [list formatter/rgen[16]*]]
add_cells_to_pblock [get_pblocks payload_17] [get_cells -quiet [list formatter/rgen[17]*]]
#add_cells_to_pblock [get_pblocks payload_18] [get_cells -quiet [list formatter/rgen[18]*]]
