from __future__ import print_function
import time, os

from SmartOpen import SmartOpen
from DepFileParser import DepFileParser
from CommandLineParser import CommandLineParser
from Pathmaker import Pathmaker

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
class AddressTableGeneratorWriter( object ):
  def __init__( self , aCommandLineArgs , aPathmaker ):
    self.CommandLineArgs = aCommandLineArgs
    self.Pathmaker = aPathmaker
 
  def write( self , aScriptVariables , aComponentPaths , aCommandList , aLibs, aMaps ):
    with SmartOpen( self.CommandLineArgs.output ) as write:
      write("# Autogenerated project build script")
      write( time.strftime("# %c") )
      write( )
      for addrtab in aCommandList["addrtab"]:
        if addrtab.TopLevel:
          n = os.path.basename( addrtab.FilePath )
          write( "gen_ipbus_addr_decode {0}".format( n ) )
          b = "ipbus_decode_{0}.vhd".format( os.path.splitext(n)[0] )
          write("cp {0} {1}".format( b , self.Pathmaker.getpath( addrtab.ComponentPath, "src", b) ) )

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
