# Datapath constraints

add_cells_to_pblock [get_pblocks quad_x1y8] [get_cells -quiet [list datapath/rgen[0].region/*]]
add_cells_to_pblock [get_pblocks quad_x1y7] [get_cells -quiet [list datapath/rgen[1].region/*]]
add_cells_to_pblock [get_pblocks quad_x1y6] [get_cells -quiet [list datapath/rgen[2].region/*]]
add_cells_to_pblock [get_pblocks quad_x1y5] [get_cells -quiet [list datapath/rgen[3].region/*]]
add_cells_to_pblock [get_pblocks quad_x1y4] [get_cells -quiet [list datapath/rgen[4].region/*]]
add_cells_to_pblock [get_pblocks quad_x1y3] [get_cells -quiet [list datapath/rgen[5].region/*]]
add_cells_to_pblock [get_pblocks quad_x1y2] [get_cells -quiet [list datapath/rgen[6].region/*]]
add_cells_to_pblock [get_pblocks quad_x1y1] [get_cells -quiet [list datapath/rgen[7].region/*]]
add_cells_to_pblock [get_pblocks quad_x1y0] [get_cells -quiet [list datapath/rgen[8].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y0] [get_cells -quiet [list datapath/rgen[9].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y1] [get_cells -quiet [list datapath/rgen[10].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y2] [get_cells -quiet [list datapath/rgen[11].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y3] [get_cells -quiet [list datapath/rgen[12].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y4] [get_cells -quiet [list datapath/rgen[13].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y5] [get_cells -quiet [list datapath/rgen[14].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y6] [get_cells -quiet [list datapath/rgen[15].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y7] [get_cells -quiet [list datapath/rgen[16].region/*]]
add_cells_to_pblock [get_pblocks quad_x0y8] [get_cells -quiet [list datapath/rgen[17].region/*]]
#add_cells_to_pblock [get_pblocks quad_x1y8] [get_cells -quiet [list datapath/rgen[18].region/*]]

# Not so easy to get from X0Y? side to X1Y? side.  Need registers located inbetween.  
add_cells_to_pblock [get_pblocks payload_8] [get_cells -quiet [list datapath/rgen[8].region/pgen.*]]

set_property LOC GTHE2_CHANNEL_X1Y32 [get_cells {datapath/rgen[0].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y33 [get_cells {datapath/rgen[0].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y34 [get_cells {datapath/rgen[0].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y35 [get_cells {datapath/rgen[0].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y8 [get_cells {datapath/rgen[0].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X1Y28 [get_cells {datapath/rgen[1].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y29 [get_cells {datapath/rgen[1].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y30 [get_cells {datapath/rgen[1].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y31 [get_cells {datapath/rgen[1].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y7 [get_cells {datapath/rgen[1].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X1Y24 [get_cells {datapath/rgen[2].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y25 [get_cells {datapath/rgen[2].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y26 [get_cells {datapath/rgen[2].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y27 [get_cells {datapath/rgen[2].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y6 [get_cells {datapath/rgen[2].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X1Y20 [get_cells {datapath/rgen[3].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y21 [get_cells {datapath/rgen[3].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y22 [get_cells {datapath/rgen[3].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y23 [get_cells {datapath/rgen[3].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y5 [get_cells {datapath/rgen[3].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X1Y16 [get_cells {datapath/rgen[4].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y17 [get_cells {datapath/rgen[4].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y18 [get_cells {datapath/rgen[4].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y19 [get_cells {datapath/rgen[4].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y4 [get_cells {datapath/rgen[4].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells {datapath/rgen[5].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y13 [get_cells {datapath/rgen[5].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y14 [get_cells {datapath/rgen[5].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y15 [get_cells {datapath/rgen[5].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y3 [get_cells {datapath/rgen[5].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X1Y8 [get_cells {datapath/rgen[6].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y9 [get_cells {datapath/rgen[6].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y10 [get_cells {datapath/rgen[6].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y11 [get_cells {datapath/rgen[6].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y2 [get_cells {datapath/rgen[6].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X1Y4 [get_cells {datapath/rgen[7].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y5 [get_cells {datapath/rgen[7].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y6 [get_cells {datapath/rgen[7].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y7 [get_cells {datapath/rgen[7].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y1 [get_cells {datapath/rgen[7].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X1Y0 [get_cells {datapath/rgen[8].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y1 [get_cells {datapath/rgen[8].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y2 [get_cells {datapath/rgen[8].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X1Y3 [get_cells {datapath/rgen[8].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X1Y0 [get_cells {datapath/rgen[8].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X0Y0 [get_cells {datapath/rgen[9].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y1 [get_cells {datapath/rgen[9].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y2 [get_cells {datapath/rgen[9].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y3 [get_cells {datapath/rgen[9].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X0Y0 [get_cells {datapath/rgen[9].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X0Y4 [get_cells {datapath/rgen[10].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y5 [get_cells {datapath/rgen[10].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y6 [get_cells {datapath/rgen[10].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y7 [get_cells {datapath/rgen[10].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X0Y1 [get_cells {datapath/rgen[10].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X0Y8 [get_cells {datapath/rgen[11].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y9 [get_cells {datapath/rgen[11].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y10 [get_cells {datapath/rgen[11].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y11 [get_cells {datapath/rgen[11].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X0Y2 [get_cells {datapath/rgen[11].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X0Y12 [get_cells {datapath/rgen[12].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y13 [get_cells {datapath/rgen[12].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y14 [get_cells {datapath/rgen[12].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y15 [get_cells {datapath/rgen[12].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X0Y3 [get_cells {datapath/rgen[12].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X0Y16 [get_cells {datapath/rgen[13].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y17 [get_cells {datapath/rgen[13].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y18 [get_cells {datapath/rgen[13].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y19 [get_cells {datapath/rgen[13].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X0Y4 [get_cells {datapath/rgen[13].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X0Y20 [get_cells {datapath/rgen[14].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y21 [get_cells {datapath/rgen[14].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y22 [get_cells {datapath/rgen[14].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y23 [get_cells {datapath/rgen[14].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X0Y5 [get_cells {datapath/rgen[14].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X0Y24 [get_cells {datapath/rgen[15].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y25 [get_cells {datapath/rgen[15].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y26 [get_cells {datapath/rgen[15].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y27 [get_cells {datapath/rgen[15].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X0Y6 [get_cells {datapath/rgen[15].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

set_property LOC GTHE2_CHANNEL_X0Y28 [get_cells {datapath/rgen[16].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y29 [get_cells {datapath/rgen[16].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y30 [get_cells {datapath/rgen[16].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_CHANNEL_X0Y31 [get_cells {datapath/rgen[16].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
set_property LOC GTHE2_COMMON_X0Y7 [get_cells {datapath/rgen[16].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]

#set_property LOC GTHE2_CHANNEL_X0Y32 [get_cells {datapath/rgen[17].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[3].gth_transceiver_i/gthe2_i}]
#set_property LOC GTHE2_CHANNEL_X0Y33 [get_cells {datapath/rgen[17].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[2].gth_transceiver_i/gthe2_i}]
#set_property LOC GTHE2_CHANNEL_X0Y34 [get_cells {datapath/rgen[17].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[1].gth_transceiver_i/gthe2_i}]
#set_property LOC GTHE2_CHANNEL_X0Y35 [get_cells {datapath/rgen[17].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/g_gt_instances[0].gth_transceiver_i/gthe2_i}]
#set_property LOC GTHE2_COMMON_X0Y8 [get_cells {datapath/rgen[17].region/mgt_gen_gth_10g.quad/quad/quad_wrapper_inst/gth_quad_i/gthe2_common_i}]



