-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_mp7_readout_control is

  constant IPBUS_SEL_WIDTH: positive := 5; -- Should be enough for now?
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_mp7_readout_control(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically  generated VHDL the Wed Mar 16 18:33:20 2016 
  constant N_SLV_CSR: integer := 0;
  constant N_SLV_BANK_CSR: integer := 1;
  constant N_SLV_CAP_CSR: integer := 2;
  constant N_SLV_MODE_CSR: integer := 3;
  constant N_SLV_HIST: integer := 4;
  constant N_SLAVES: integer := 5;
-- END automatically generated VHDL

    
end ipbus_decode_mp7_readout_control;

package body ipbus_decode_mp7_readout_control is

  function ipbus_sel_mp7_readout_control(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically  generated VHDL the Wed Mar 16 18:33:20 2016 
    if    std_match(addr, "--------------------------0000--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CSR, IPBUS_SEL_WIDTH)); -- csr / base 0x00000000 / mask 0x0000003c
    elsif std_match(addr, "--------------------------0001--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_BANK_CSR, IPBUS_SEL_WIDTH)); -- bank_csr / base 0x00000004 / mask 0x0000003c
    elsif std_match(addr, "--------------------------0010--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CAP_CSR, IPBUS_SEL_WIDTH)); -- cap_csr / base 0x00000008 / mask 0x0000003c
    elsif std_match(addr, "--------------------------010---") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_MODE_CSR, IPBUS_SEL_WIDTH)); -- mode_csr / base 0x00000010 / mask 0x00000038
    elsif std_match(addr, "--------------------------1000--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_HIST, IPBUS_SEL_WIDTH)); -- hist / base 0x00000020 / mask 0x0000003c
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_mp7_readout_control;

end ipbus_decode_mp7_readout_control;

